#!/bin/bash
#PBS -l nodes=2:ppn=2,walltime=2:00
#PBS -l naccesspolicy=singlejob
#PBS -N pddrive
#PBS -V

cd $PBS_O_WORKDIR

export MV2_HOMOGENEOUS_CLUSTER=1
export MV2_SUPPRESS_JOB_STARTUP_PERFORMANCE_WARNING=1
#export MV2_ENABLE_AFFINITY=0

HASH=$(spack find --format /{hash} superlu-dist@8: ~cuda | head -1)
SUPERLU_DIST_ROOT=$(spack location -i $HASH)
spack load $HASH
export LD_LIBRARY_PATH=$SUPERLU_DIST_ROOT/lib:$LD_LIBRARY_PATH

mpirun ./pddrive -r 2 -c 2 g20.rua
